#ifndef KEYWORDS_H
#define KEYWORDS_H

//enumeration of keywords for the parser
enum Keywords
{
    SELECT,INTO,FROM,WHERE,TABLE,INSERT,CREATE,EXIT,STRING,VALUES,DROP,LIST_TABLES,
    EXEC,ASTERISK,COMMA,QUOTE,OPEN_PARENTH,CLOSED_PARENTH,RELATIONAL_OPERATOR,
    LOGICAL_OPERATOR,FIELDS

};

#endif // KEYWORDS_H
